name: Linting and tests

on:
  pull_request:
    branches: 
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.5
      uses: actions/setup-node@v1
      with:
        node-version: 16.5.x
    - name: npm install
      run: |
        npm ci && npm install --no-save
      env:
        npm_config_userconfig: "./.npmrc"
      shell: bash
    - name: lint
      run: |
        npm run lint
    - name: tsc
      run: |
        npm run tsc
    - name: build
      run: |
        npm run build
      env:
        CI: true
        TAP_BAIL: 1
